### ISSUE TITLE
根节点互换位置有bug，拖拽的节点会把插入位置的节点替换掉，官方demo可复现

### ISSUE THREAD

**Issue by thinkif** [ltaoo/vue-draggable-tree#5]
复现方式：
拖拽第一个根节点（女装），拽到第二个根节点（男装）下方，但两者平级，不是拉到男装的子节点位置，此时女装节点将男装覆盖，即前两个根节点都是女装。

而期待的效果应该是第一个根节点为男装，第二个根节点为女装。

**Comment by adamma1024** [comment]
我也发现了

**Comment by zhuSilence** [comment]
好像移动同一级别的（上下换位置）都是有这个问题，不单单是根节点

**Comment by ltaoo** [comment]
1.1.6 版本修复了
